name: baidu_location_example
description: Demonstrates how to use the baidu_location plugin.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  easy_alert: any
  baidu_location:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  baidu_location:
    path: ../

flutter:
  uses-material-design: true
